DROP TABLE IF EXISTS PROFESOR_MODULO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE  IF EXISTS PROFESOR_ROL;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS IMAGEN;
DROP TABLE IF EXISTS PROFESOR;






CREATE TABLE PROFESOR
(
   ID_PROFESOR SERIAL PRIMARY KEY,
   NOMBRE TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   NICKNAME TEXT NOT NULL,
   APELLIDOS TEXT NOT NULL
);

CREATE TABLE IMAGEN
(
   ID_IMAGEN SERIAL PRIMARY KEY,
   NOMBRE TEXT NOT NULL,
   IMAGEN BYTEA NOT NULL,
   ID_PROFESOR INT NOT NULL,
   CONSTRAINT FK_IMAGEN_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR) ON UPDATE CASCADE 
   
);

CREATE TABLE ROL
(
   ID_ROL SERIAL PRIMARY KEY,
   NOMBRE_ROL TEXT NOT NULL
);

CREATE TABLE PROFESOR_ROL
(
   ID_PROFESOR INT NOT NULL,
   ID_ROL INT NOT NULL,
      PRIMARY KEY
   (
      ID_PROFESOR,
      ID_ROL
   ),
   CONSTRAINT FK_PROFESOR_ROL_1 FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR) ON DELETE CASCADE,
   CONSTRAINT FK_PROFESOR_ROL_2 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE EMAIL
(
   ID_EMAIL SERIAL PRIMARY KEY,
   DIRECCION_EMAIL TEXT NOT NULL,
   ID_PROFESOR INT NOT NULL,
   CONSTRAINT FK_EMAIL_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR) ON UPDATE CASCADE 
);

CREATE TABLE MODULO
(
   ID_MODULO SERIAL PRIMARY KEY,
   NOMBRE_MODULO TEXT NOT NULL
);

CREATE TABLE PROFESOR_MODULO
(
   ID_PROFESOR INT NOT NULL,
   ID_MODULO INT NOT NULL,
   PRIMARY KEY
   (
      ID_PROFESOR,
      ID_MODULO
   ),
   CONSTRAINT FK_PROFESOR_MODULO_1 FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR) ON DELETE CASCADE,
   CONSTRAINT FK_PROFESOR_MODULO_2 FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO)
);